name: zoe
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cuda-toolkit=12.1
  - h5py=3.8.0
  - hdf5=1.12.2
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - numpy=1.24.3
  - opencv=4.8.1
  - pip=23.3.1
  - python=3.10.13
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - scipy=1.11.4
  - torchaudio=2.2.0
  - torchvision=0.17.0
  - pip:
    - huggingface-hub==0.18.0
    - timm==0.9.12
    - tqdm==4.66.1
    - wandb==0.15.12
